#--------------------------------- Self managed Consul Cluster ---------------------------------

global:
  enabled: true
  datacenter: dc1
  name: consul
  image: hashicorp/consul:1.15.2
  imageConsulDataplane: hashicorp/consul-dataplane:1.1.0
  imageK8S: hashicorp/consul-k8s-control-plane:1.1.1
  acls:
    manageSystemACLs: true
  tls:
    enabled: true
  metrics:
    enabled: true

# meshGateway:
#   enabled: false
#   service:
#     annotations: |
#       service.beta.kubernetes.io/aws-load-balancer-internal: "true"
#       service.beta.kubernetes.io/aws-load-balancer-scheme: internal
#       service.beta.kubernetes.io/aws-load-balancer-type: nlb

terminatingGateways:
  enabled: true

apiGateway:
  enabled: true
  image: hashicorp/consul-api-gateway:0.5.3
  imageEnvoy: envoyproxy/envoy:v1.25.1
  managedGatewayClass:
    serviceType: NodePort
    useHostPorts: true

connectInject:
  enabled: true
  default: true
  k8sAllowNamespaces: ['default', 'consul']

server:
 enabled: true
 replicas: 3

ui:
 enabled: true
 service:
   enabled: true
   type: LoadBalancer
   annotations: |
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-name: consul-lb
