apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: fake-service
spec:
  protocol: http
---
apiVersion: v1
kind: Service
metadata:
  name: fake-service
  labels:
    app: fake-service
spec:
  type: NodePort
  selector:
    app: fake-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9090
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fake-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-service
  labels:
    app: fake-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-service
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/service-meta-version: "v1"
        consul.hashicorp.com/service-tags: "v1"
      labels:
        app: fake-service
    spec:
      serviceAccountName: fake-service
      containers:
        - name: fake-service
          image: "nicholasjackson/fake-service:v0.19.1"
          ports:
            - containerPort: 9090
          env:
            - name: NAME
              value: "fake-service"
            - name: MESSAGE
              value: "Hello from fake-service V1 !!"
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-service-2
  labels:
    app: fake-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-service
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/service-meta-version: "v2"
        consul.hashicorp.com/service-tags: "v2"
      labels:
        app: fake-service
    spec:
      serviceAccountName: fake-service
      containers:
        - name: fake-service
          image: "nicholasjackson/fake-service:v0.19.1"
          ports:
            - containerPort: 9090
          env:
            - name: NAME
              value: "fake-service"
            - name: MESSAGE
              value: "Hello from fake-service V2 !!"
            - name: ERROR_TYPE
              value: "http_error"
            - name: ERROR_CODE
              value: "500"
            - name: ERROR_RATE
              value: "1.0"
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 3
            periodSeconds: 3