apiVersion: v1
kind: Service
metadata:
  name: rollouts-service #not only SA but also a service needs to be created when it is refered from consul.hashicorp.com/connect-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: rollouts-demo
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-service-v1
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: rollouts-demo
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-service-v2
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: rollouts-demo
  type: NodePort

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rollouts-service
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rollouts-service-v1
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rollouts-service-v2
  namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rollouts-demo
  namespace: default

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: rollouts-service
spec:
  protocol: http
  mutualTLSMode: permissive
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: rollouts-service-v1
spec:
  protocol: http
  mutualTLSMode: permissive
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: rollouts-service-v2
spec:
  protocol: http
  mutualTLSMode: permissive


