apiVersion: v1
kind: Service
metadata:
  name: rollouts-service
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: rollouts-demo
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: rollouts-service-v1
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: rollouts-demo
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: rollouts-service-v2
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: rollouts-demo
  type: NodePort

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rollouts-service
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rollouts-service-v1
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rollouts-service-v2
  namespace: default