apiVersion: v1
kind: ServiceAccount
metadata:
  name: counting
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: counting
  name: counting
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counting
  template:
    metadata:
      name: counting
      annotations:
        consul.hashicorp.com/connect-service: "counting"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy: "true"
      labels:
        app: counting
    spec:
      serviceAccountName: counting
      containers:
      - name: counting
        image: hashicorp/counting-service:0.0.2
        ports:
        - name: http
          containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: counting
  name: counting
  namespace: default
spec:
  type: NodePort
  selector:
    app: counting
  ports:
  - port: 9001
    targetPort: 9001


